engine:
  rpc:
    port: 9191
    host: 0.0.0.0

  storage:
    type: filesystem
    config:
      root: /var/lib/paladin/storage

  domain:
    type: pente

  http:
    url: http://172.16.239.11:8545
    chainId: 1337

  identity:
    keystore:
      path: /var/lib/paladin/keystore
      password: changeit

logging:
  level: INFO