@startuml
skinparam monochrome true
skinparam packageStyle frame
skinparam defaultFontName Arial


package "Client" {
    [IoT Device/ App] as IoT
}

package "Oracle " {
    [Data Obfuscation] as Oracle
}

package "Blockchain" {
    [Smart Contract] as SC
}



@enduml