@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial

start
:Cryptographic Seed;
note right: Set of 12 words

repeat
  :Identity Derivation;
  note right: Unique Pseudonym for the Session
  
  :Telemetry Submission and Receipt of Incentives;
  
backward: Start New Session;
repeat while (Perform new submission?) is (Yes)

stop
@enduml