@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial

start
:Coleta de Telemetria Bruta;

if (Deseja aplicar Offset?) then (Sim)
  partition "Oráculo " {
    repeat
      :Gerar Candidato de Deslocamento;
      :Projetar na Malha Viária;
      :Calcular Penalização de Monetização;
    backward: Iterar (n vezes);
    repeat while (Busca concluída?) is (Não)
    :Apresentar 5 Melhores Opções;
    :Usuário Seleciona Opção;
  }
else (Não)
  :Manter Trajetória Original;

endif

if (Deseja usar Pseudônimo?) then (Sim)
  :Gerar Carteira Pseudônima;
  :Vincular Registro ao Pseudônimo;

else (Não)
  :Vincular Registro à Identidade Real;

endif

:Registro na Blockchain;
stop
@enduml