@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial

start
:Coleta de Telemetria Bruta;

if (Deseja aplicar Offset?) then (Sim)
  partition "Processamento do Oráculo" {
    repeat
      :Buscar Candidato de Deslocamento;
      :Projetar na Malha Viária;
      :Validar Monetização < 100%;
    backward: Iterar (n vezes);
    repeat while (Busca concluída?) is (Não)
    :Apresentar 5 Melhores Opções;
    :Usuário Seleciona Opção;
  }
else (Não)
  :Manter Trajetória Original;
endif

if (Deseja usar Pseudônimo?) then (Sim)
  :Gerar Pseudônimo;
  :Vincular Trajeto ao Pseudônimo;
  :Submissão via Cenário 3;
else (Não)
  if (Deseja Anonimato de Trajeto (ZKP)?) then (Sim)
    :Vincular Trajeto ao Hash;
    :Submissão via Cenário 2;
  else (Não)
    :Vincular à Identidade Real;
    :Submissão via Cenário 1;
  endif
endif

:Registro na Blockchain;
stop
@enduml