@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial

start
:Semente Criptográfica;


repeat
  :Derivação de Identidade;
  note right: Pseudônimo Único para a Sessão
  
  :Submissão de Telemetria e Recebimento de Incentivos;
  
backward: Iniciar Nova Sessão;
repeat while (Realizar nova submissão?) is (Sim)

stop
@enduml