@startuml
skinparam conditionStyle diamond
skinparam style strictuml
|Client|
start
:Local Preparation;
|Oracle|
:Obfuscation Processing;
:Provide Options;
|Client|
:Route Selection;
|Oracle|
:Registry on Blockchain;
|Blockchain|
:Reward Custody;
|Client|
:Claim Request\n(Proof);
|Blockchain|
:ZKP Verification;
if (Valid Proof?) then (Yes)
    |Blockchain|
    :Transfer Balance;
else (No)
    |Blockchain|
    :Reject Request;
endif
|Client|
stop
@enduml