@startuml
skinparam conditionStyle diamond
skinparam style strictuml

|User|
start
:Local Preparation;

|Oracle|
:Obfuscation Processing;
:Provide Options;

|User|
:Route Selection;

|Oracle|
:Registry on Blockchain;

|Blockchain|
:Reward Custody;

|User|
:Claim Request\n(Proof);

|Oracle|
:ZKP Verification;
if (Valid Proof?) then (Yes)
    |Oracle|
    :Transfer Balance;
else (No)
    |Oracle|
    :Reject Request;
endif

|User|
stop
@enduml